/* The GLES and EGL entry points a core calls directly, forwarded to the frontend's context.
 *
 * WHY A CORE HAS UNDEFINED GL SYMBOLS AT ALL, WHICH IS THE PART WORTH UNDERSTANDING.
 * libretro's glsym layer turns MOST GL calls into macros over function pointers it resolves at
 * run time (libretro-common/include/glsym/glsym_es3.h). It deliberately does not do that for the
 * functions that are part of the GLES core ABI - glBindFramebuffer, glDrawArrays and the rest -
 * because on every ordinary platform those come from libGLESv2.so and the dynamic linker resolves
 * them against whatever the process already loaded. A .prx has its own symbol table and no
 * dynamic linker to ask, so they arrive here as plain undefined symbols.
 *
 * AND LINKING MESA'S libGLESv2.a INTO THE MODULE WOULD BE THE WRONG FIX, not merely a larger one.
 * That archive is the mapi DISPATCH TABLE: every call reads the current thread's dispatch pointer
 * and jumps through it. The context is made current in the FRONTEND's copy of that table, so a
 * second copy inside the module would be empty - every call jumping through a null slot. Two
 * dispatch tables, one context, and the symptom would be a crash in the first GL call that looked
 * like a driver fault.
 *
 * So each entry point below is a THUNK that jumps to the frontend's implementation, resolved once
 * through the proc-address function the frontend handed the core.
 *
 * THE THUNKS ARE ASSEMBLY AND THAT IS WHAT MAKES THEM CORRECT. A C forwarder would need the exact
 * prototype of all hundred-odd functions, and a wrong one is not a compile error - it is arguments
 * passed in the wrong registers, silently. A jmp through a pointer preserves every register the
 * caller set up, whatever the signature, which is precisely what a PLT stub does and for the same
 * reason. Nothing here needs to know what glTexImage3D takes.
 *
 * GENERATED from the undefined symbols of a core linked without it. To regenerate: link, collect
 * ld.lld's "undefined symbol:" lines, feed them back in.
 *
 * SPDX-License-Identifier: MIT
 */
#include <stddef.h>

#include "orbis_report.h"

/* WEAK, because a core that never touches GL must still link if this member is pulled for
 * something else. glsm_ctl is where the proc-address function lives: the frontend gives it to the
 * core in retro_hw_render_callback, glsm keeps it, and GLSM_CTL_PROC_ADDRESS_GET hands it back. */
#define GLSM_CTL_PROC_ADDRESS_GET 12
__attribute__((weak)) int glsm_ctl(int state, void *data);

typedef void (*orbis_gl_proc_t)(void);
typedef orbis_gl_proc_t (*orbis_gl_getproc_t)(const char *sym);

static const char *const orbis_gl_names[] = {
   "eglGetDisplay",
   "eglGetProcAddress",
   "eglInitialize",
   "eglQueryString",
   "glActiveTexture",
   "glAttachShader",
   "glBeginQuery",
   "glBindAttribLocation",
   "glBindBuffer",
   "glBindBufferBase",
   "glBindFramebuffer",
   "glBindRenderbuffer",
   "glBindSampler",
   "glBindTexture",
   "glBindVertexArray",
   "glBlendColor",
   "glBlendEquation",
   "glBlendEquationSeparate",
   "glBlendFunc",
   "glBlendFuncSeparate",
   "glBlitFramebuffer",
   "glBufferData",
   "glBufferSubData",
   "glCheckFramebufferStatus",
   "glClear",
   "glClearColor",
   "glClearDepthf",
   "glClientWaitSync",
   "glColorMask",
   "glCompileShader",
   "glCompressedTexImage2D",
   "glCreateProgram",
   "glCreateShader",
   "glCullFace",
   "glDeleteBuffers",
   "glDeleteFramebuffers",
   "glDeleteProgram",
   "glDeleteQueries",
   "glDeleteRenderbuffers",
   "glDeleteShader",
   "glDeleteSync",
   "glDeleteTextures",
   "glDeleteVertexArrays",
   "glDepthFunc",
   "glDepthMask",
   "glDepthRangef",
   "glDetachShader",
   "glDisable",
   "glDisableVertexAttribArray",
   "glDrawArrays",
   "glDrawBuffers",
   "glDrawElements",
   "glEnable",
   "glEnableVertexAttribArray",
   "glEndQuery",
   "glFenceSync",
   "glFlushMappedBufferRange",
   "glFramebufferRenderbuffer",
   "glFramebufferTexture2D",
   "glFrontFace",
   "glGenBuffers",
   "glGenerateMipmap",
   "glGenFramebuffers",
   "glGenQueries",
   "glGenRenderbuffers",
   "glGenSamplers",
   "glGenTextures",
   "glGenVertexArrays",
   "glGetActiveUniform",
   "glGetActiveUniformBlockiv",
   "glGetActiveUniformsiv",
   "glGetAttribLocation",
   "glGetError",
   "glGetFramebufferAttachmentParameteriv",
   "glGetInteger64v",
   "glGetIntegerv",
   "glGetProgramBinary",
   "glGetProgramInfoLog",
   "glGetProgramiv",
   "glGetQueryObjectuiv",
   "glGetShaderInfoLog",
   "glGetShaderiv",
   "glGetStringi",
   "glGetUniformBlockIndex",
   "glGetUniformIndices",
   "glGetUniformLocation",
   "glIsProgram",
   "glLineWidth",
   "glLinkProgram",
   "glMapBufferRange",
   "glPixelStorei",
   "glPolygonOffset",
   "glProgramParameteri",
   "glReadBuffer",
   "glReadPixels",
   "glRenderbufferStorage",
   "glSamplerParameteri",
   "glScissor",
   "glShaderSource",
   "glStencilFunc",
   "glStencilMask",
   "glStencilOp",
   "glTexImage3D",
   "glTexStorage2D",
   "glTexSubImage2D",
   "glUniform1f",
   "glUniform1fv",
   "glUniform1i",
   "glUniform1iv",
   "glUniform1ui",
   "glUniform2f",
   "glUniform2fv",
   "glUniform2i",
   "glUniform2iv",
   "glUniform2ui",
   "glUniform2uiv",
   "glUniform3f",
   "glUniform3fv",
   "glUniform3ui",
   "glUniform4f",
   "glUniform4fv",
   "glUniform4i",
   "glUniform4ui",
   "glUniformBlockBinding",
   "glUniformMatrix4fv",
   "glUseProgram",
   "glValidateProgram",
   "glVertexAttrib4f",
   "glVertexAttrib4fv",
   "glVertexAttribIPointer",
   "glVertexAttribPointer",
   "glViewport",
   "glWaitSync",
   /* ⚠ APPENDED, NEVER INSERTED. Each thunk below carries its slot as a literal byte offset -
    * index * 8 - so putting a name in alphabetical order would silently renumber every thunk
    * after it. Anything new goes on the end, whatever it looks like. These three came from
    * Play!, which reaches them directly rather than through glsm's macros. */
   "glTexImage2D",
   "glTexParameteri",
   "glRenderbufferStorageMultisample",
   NULL
};

void *orbis_gl_slot[137];

/* Called before the first GL call of a context - see the core patch that calls it from
 * context_reset. Resolving eagerly rather than lazily keeps the thunks to four instructions and
 * means a missing entry point is reported at a known moment instead of at a random draw call. */
/* ⚠ THE PROC-ADDRESS FUNCTION DOES NOT ONLY COME FROM glsm, AND ASSUMING IT DID COST A CORE.
 * glsm is libretro-common's GL state manager and most GL cores use it, so GLSM_CTL_PROC_ADDRESS_GET
 * was the only way in here. Play! does not use glsm at all - it keeps its own
 * retro_hw_render_callback and calls the GLES core ABI directly - so orbis_gl_resolve() found no
 * glsm_ctl, reported "no glsm in this core", and every thunk stayed null. The frontend hands
 * get_proc_address to EVERY hardware-rendered core in that callback, whether or not glsm is in the
 * middle, so a core that has it can pass it straight in. */
int orbis_gl_resolve_proc(orbis_gl_getproc_t getproc)
{
   unsigned i, missing = 0;

   if (!getproc)
   {
      orbis_report("gl", "the frontend gave this core no proc-address function");
      return 0;
   }

   for (i = 0; orbis_gl_names[i]; i++)
   {
      orbis_gl_slot[i] = (void*)getproc(orbis_gl_names[i]);
      if (!orbis_gl_slot[i])
      {
         /* NAMED, NOT COUNTED. "17 entry points missing" sends the reader off to guess which; a
          * name says whether the driver lacks an extension or the context is the wrong version.
          * Capped so a wholly unresolved table cannot fill the log. */
         if (missing < 12)
            orbis_report("gl", "unresolved: %s", orbis_gl_names[i]);
         missing++;
      }
   }

   orbis_report("gl", "%u entry points resolved, %u missing", i - missing, missing);
   return missing == 0;
}

int orbis_gl_resolve(void)
{
   orbis_gl_getproc_t getproc = NULL;

   if (!glsm_ctl)
   {
      orbis_report("gl", "no glsm in this core - pass get_proc_address to "
                         "orbis_gl_resolve_proc() instead");
      return 0;
   }
   if (!glsm_ctl(GLSM_CTL_PROC_ADDRESS_GET, &getproc))
      getproc = NULL;
   return orbis_gl_resolve_proc(getproc);
}

/* Reached only if something calls GL before the context was resolved, which is a bug in the
 * caller rather than a condition to recover from: there is no correct value to return for an
 * arbitrary GL function. */
void orbis_gl_unresolved(void)
{
   orbis_report("gl", "a GL entry point was called before the context was resolved");
   __builtin_trap();
}

/* The thunks: load the slot, check it, jump. */
__asm__(
   ".globl eglGetDisplay\n"
   ".type eglGetDisplay,@function\n"
   "eglGetDisplay:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 0(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl eglGetProcAddress\n"
   ".type eglGetProcAddress,@function\n"
   "eglGetProcAddress:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 8(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl eglInitialize\n"
   ".type eglInitialize,@function\n"
   "eglInitialize:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 16(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl eglQueryString\n"
   ".type eglQueryString,@function\n"
   "eglQueryString:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 24(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glActiveTexture\n"
   ".type glActiveTexture,@function\n"
   "glActiveTexture:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 32(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glAttachShader\n"
   ".type glAttachShader,@function\n"
   "glAttachShader:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 40(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBeginQuery\n"
   ".type glBeginQuery,@function\n"
   "glBeginQuery:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 48(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindAttribLocation\n"
   ".type glBindAttribLocation,@function\n"
   "glBindAttribLocation:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 56(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindBuffer\n"
   ".type glBindBuffer,@function\n"
   "glBindBuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 64(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindBufferBase\n"
   ".type glBindBufferBase,@function\n"
   "glBindBufferBase:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 72(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindFramebuffer\n"
   ".type glBindFramebuffer,@function\n"
   "glBindFramebuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 80(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindRenderbuffer\n"
   ".type glBindRenderbuffer,@function\n"
   "glBindRenderbuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 88(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindSampler\n"
   ".type glBindSampler,@function\n"
   "glBindSampler:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 96(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindTexture\n"
   ".type glBindTexture,@function\n"
   "glBindTexture:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 104(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBindVertexArray\n"
   ".type glBindVertexArray,@function\n"
   "glBindVertexArray:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 112(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlendColor\n"
   ".type glBlendColor,@function\n"
   "glBlendColor:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 120(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlendEquation\n"
   ".type glBlendEquation,@function\n"
   "glBlendEquation:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 128(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlendEquationSeparate\n"
   ".type glBlendEquationSeparate,@function\n"
   "glBlendEquationSeparate:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 136(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlendFunc\n"
   ".type glBlendFunc,@function\n"
   "glBlendFunc:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 144(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlendFuncSeparate\n"
   ".type glBlendFuncSeparate,@function\n"
   "glBlendFuncSeparate:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 152(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBlitFramebuffer\n"
   ".type glBlitFramebuffer,@function\n"
   "glBlitFramebuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 160(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBufferData\n"
   ".type glBufferData,@function\n"
   "glBufferData:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 168(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glBufferSubData\n"
   ".type glBufferSubData,@function\n"
   "glBufferSubData:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 176(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCheckFramebufferStatus\n"
   ".type glCheckFramebufferStatus,@function\n"
   "glCheckFramebufferStatus:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 184(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glClear\n"
   ".type glClear,@function\n"
   "glClear:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 192(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glClearColor\n"
   ".type glClearColor,@function\n"
   "glClearColor:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 200(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glClearDepthf\n"
   ".type glClearDepthf,@function\n"
   "glClearDepthf:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 208(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glClientWaitSync\n"
   ".type glClientWaitSync,@function\n"
   "glClientWaitSync:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 216(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glColorMask\n"
   ".type glColorMask,@function\n"
   "glColorMask:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 224(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCompileShader\n"
   ".type glCompileShader,@function\n"
   "glCompileShader:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 232(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCompressedTexImage2D\n"
   ".type glCompressedTexImage2D,@function\n"
   "glCompressedTexImage2D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 240(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCreateProgram\n"
   ".type glCreateProgram,@function\n"
   "glCreateProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 248(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCreateShader\n"
   ".type glCreateShader,@function\n"
   "glCreateShader:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 256(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glCullFace\n"
   ".type glCullFace,@function\n"
   "glCullFace:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 264(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteBuffers\n"
   ".type glDeleteBuffers,@function\n"
   "glDeleteBuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 272(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteFramebuffers\n"
   ".type glDeleteFramebuffers,@function\n"
   "glDeleteFramebuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 280(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteProgram\n"
   ".type glDeleteProgram,@function\n"
   "glDeleteProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 288(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteQueries\n"
   ".type glDeleteQueries,@function\n"
   "glDeleteQueries:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 296(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteRenderbuffers\n"
   ".type glDeleteRenderbuffers,@function\n"
   "glDeleteRenderbuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 304(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteShader\n"
   ".type glDeleteShader,@function\n"
   "glDeleteShader:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 312(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteSync\n"
   ".type glDeleteSync,@function\n"
   "glDeleteSync:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 320(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteTextures\n"
   ".type glDeleteTextures,@function\n"
   "glDeleteTextures:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 328(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDeleteVertexArrays\n"
   ".type glDeleteVertexArrays,@function\n"
   "glDeleteVertexArrays:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 336(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDepthFunc\n"
   ".type glDepthFunc,@function\n"
   "glDepthFunc:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 344(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDepthMask\n"
   ".type glDepthMask,@function\n"
   "glDepthMask:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 352(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDepthRangef\n"
   ".type glDepthRangef,@function\n"
   "glDepthRangef:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 360(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDetachShader\n"
   ".type glDetachShader,@function\n"
   "glDetachShader:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 368(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDisable\n"
   ".type glDisable,@function\n"
   "glDisable:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 376(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDisableVertexAttribArray\n"
   ".type glDisableVertexAttribArray,@function\n"
   "glDisableVertexAttribArray:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 384(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDrawArrays\n"
   ".type glDrawArrays,@function\n"
   "glDrawArrays:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 392(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDrawBuffers\n"
   ".type glDrawBuffers,@function\n"
   "glDrawBuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 400(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glDrawElements\n"
   ".type glDrawElements,@function\n"
   "glDrawElements:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 408(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glEnable\n"
   ".type glEnable,@function\n"
   "glEnable:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 416(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glEnableVertexAttribArray\n"
   ".type glEnableVertexAttribArray,@function\n"
   "glEnableVertexAttribArray:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 424(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glEndQuery\n"
   ".type glEndQuery,@function\n"
   "glEndQuery:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 432(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glFenceSync\n"
   ".type glFenceSync,@function\n"
   "glFenceSync:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 440(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glFlushMappedBufferRange\n"
   ".type glFlushMappedBufferRange,@function\n"
   "glFlushMappedBufferRange:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 448(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glFramebufferRenderbuffer\n"
   ".type glFramebufferRenderbuffer,@function\n"
   "glFramebufferRenderbuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 456(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glFramebufferTexture2D\n"
   ".type glFramebufferTexture2D,@function\n"
   "glFramebufferTexture2D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 464(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glFrontFace\n"
   ".type glFrontFace,@function\n"
   "glFrontFace:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 472(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenBuffers\n"
   ".type glGenBuffers,@function\n"
   "glGenBuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 480(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenerateMipmap\n"
   ".type glGenerateMipmap,@function\n"
   "glGenerateMipmap:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 488(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenFramebuffers\n"
   ".type glGenFramebuffers,@function\n"
   "glGenFramebuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 496(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenQueries\n"
   ".type glGenQueries,@function\n"
   "glGenQueries:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 504(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenRenderbuffers\n"
   ".type glGenRenderbuffers,@function\n"
   "glGenRenderbuffers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 512(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenSamplers\n"
   ".type glGenSamplers,@function\n"
   "glGenSamplers:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 520(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenTextures\n"
   ".type glGenTextures,@function\n"
   "glGenTextures:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 528(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGenVertexArrays\n"
   ".type glGenVertexArrays,@function\n"
   "glGenVertexArrays:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 536(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetActiveUniform\n"
   ".type glGetActiveUniform,@function\n"
   "glGetActiveUniform:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 544(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetActiveUniformBlockiv\n"
   ".type glGetActiveUniformBlockiv,@function\n"
   "glGetActiveUniformBlockiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 552(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetActiveUniformsiv\n"
   ".type glGetActiveUniformsiv,@function\n"
   "glGetActiveUniformsiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 560(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetAttribLocation\n"
   ".type glGetAttribLocation,@function\n"
   "glGetAttribLocation:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 568(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetError\n"
   ".type glGetError,@function\n"
   "glGetError:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 576(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetFramebufferAttachmentParameteriv\n"
   ".type glGetFramebufferAttachmentParameteriv,@function\n"
   "glGetFramebufferAttachmentParameteriv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 584(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetInteger64v\n"
   ".type glGetInteger64v,@function\n"
   "glGetInteger64v:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 592(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetIntegerv\n"
   ".type glGetIntegerv,@function\n"
   "glGetIntegerv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 600(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetProgramBinary\n"
   ".type glGetProgramBinary,@function\n"
   "glGetProgramBinary:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 608(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetProgramInfoLog\n"
   ".type glGetProgramInfoLog,@function\n"
   "glGetProgramInfoLog:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 616(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetProgramiv\n"
   ".type glGetProgramiv,@function\n"
   "glGetProgramiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 624(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetQueryObjectuiv\n"
   ".type glGetQueryObjectuiv,@function\n"
   "glGetQueryObjectuiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 632(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetShaderInfoLog\n"
   ".type glGetShaderInfoLog,@function\n"
   "glGetShaderInfoLog:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 640(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetShaderiv\n"
   ".type glGetShaderiv,@function\n"
   "glGetShaderiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 648(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetStringi\n"
   ".type glGetStringi,@function\n"
   "glGetStringi:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 656(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetUniformBlockIndex\n"
   ".type glGetUniformBlockIndex,@function\n"
   "glGetUniformBlockIndex:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 664(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetUniformIndices\n"
   ".type glGetUniformIndices,@function\n"
   "glGetUniformIndices:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 672(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glGetUniformLocation\n"
   ".type glGetUniformLocation,@function\n"
   "glGetUniformLocation:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 680(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glIsProgram\n"
   ".type glIsProgram,@function\n"
   "glIsProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 688(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glLineWidth\n"
   ".type glLineWidth,@function\n"
   "glLineWidth:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 696(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glLinkProgram\n"
   ".type glLinkProgram,@function\n"
   "glLinkProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 704(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glMapBufferRange\n"
   ".type glMapBufferRange,@function\n"
   "glMapBufferRange:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 712(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glPixelStorei\n"
   ".type glPixelStorei,@function\n"
   "glPixelStorei:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 720(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glPolygonOffset\n"
   ".type glPolygonOffset,@function\n"
   "glPolygonOffset:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 728(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glProgramParameteri\n"
   ".type glProgramParameteri,@function\n"
   "glProgramParameteri:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 736(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glReadBuffer\n"
   ".type glReadBuffer,@function\n"
   "glReadBuffer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 744(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glReadPixels\n"
   ".type glReadPixels,@function\n"
   "glReadPixels:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 752(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glRenderbufferStorage\n"
   ".type glRenderbufferStorage,@function\n"
   "glRenderbufferStorage:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 760(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glSamplerParameteri\n"
   ".type glSamplerParameteri,@function\n"
   "glSamplerParameteri:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 768(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glScissor\n"
   ".type glScissor,@function\n"
   "glScissor:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 776(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glShaderSource\n"
   ".type glShaderSource,@function\n"
   "glShaderSource:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 784(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glStencilFunc\n"
   ".type glStencilFunc,@function\n"
   "glStencilFunc:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 792(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glStencilMask\n"
   ".type glStencilMask,@function\n"
   "glStencilMask:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 800(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glStencilOp\n"
   ".type glStencilOp,@function\n"
   "glStencilOp:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 808(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glTexImage3D\n"
   ".type glTexImage3D,@function\n"
   "glTexImage3D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 816(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glTexStorage2D\n"
   ".type glTexStorage2D,@function\n"
   "glTexStorage2D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 824(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glTexImage2D\n"
   ".type glTexImage2D,@function\n"
   "glTexImage2D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1064(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glTexParameteri\n"
   ".type glTexParameteri,@function\n"
   "glTexParameteri:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1072(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glRenderbufferStorageMultisample\n"
   ".type glRenderbufferStorageMultisample,@function\n"
   "glRenderbufferStorageMultisample:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1080(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glTexSubImage2D\n"
   ".type glTexSubImage2D,@function\n"
   "glTexSubImage2D:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 832(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform1f\n"
   ".type glUniform1f,@function\n"
   "glUniform1f:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 840(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform1fv\n"
   ".type glUniform1fv,@function\n"
   "glUniform1fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 848(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform1i\n"
   ".type glUniform1i,@function\n"
   "glUniform1i:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 856(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform1iv\n"
   ".type glUniform1iv,@function\n"
   "glUniform1iv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 864(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform1ui\n"
   ".type glUniform1ui,@function\n"
   "glUniform1ui:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 872(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2f\n"
   ".type glUniform2f,@function\n"
   "glUniform2f:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 880(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2fv\n"
   ".type glUniform2fv,@function\n"
   "glUniform2fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 888(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2i\n"
   ".type glUniform2i,@function\n"
   "glUniform2i:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 896(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2iv\n"
   ".type glUniform2iv,@function\n"
   "glUniform2iv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 904(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2ui\n"
   ".type glUniform2ui,@function\n"
   "glUniform2ui:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 912(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform2uiv\n"
   ".type glUniform2uiv,@function\n"
   "glUniform2uiv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 920(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform3f\n"
   ".type glUniform3f,@function\n"
   "glUniform3f:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 928(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform3fv\n"
   ".type glUniform3fv,@function\n"
   "glUniform3fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 936(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform3ui\n"
   ".type glUniform3ui,@function\n"
   "glUniform3ui:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 944(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform4f\n"
   ".type glUniform4f,@function\n"
   "glUniform4f:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 952(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform4fv\n"
   ".type glUniform4fv,@function\n"
   "glUniform4fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 960(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform4i\n"
   ".type glUniform4i,@function\n"
   "glUniform4i:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 968(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniform4ui\n"
   ".type glUniform4ui,@function\n"
   "glUniform4ui:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 976(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniformBlockBinding\n"
   ".type glUniformBlockBinding,@function\n"
   "glUniformBlockBinding:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 984(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUniformMatrix4fv\n"
   ".type glUniformMatrix4fv,@function\n"
   "glUniformMatrix4fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 992(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glUseProgram\n"
   ".type glUseProgram,@function\n"
   "glUseProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1000(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glValidateProgram\n"
   ".type glValidateProgram,@function\n"
   "glValidateProgram:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1008(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glVertexAttrib4f\n"
   ".type glVertexAttrib4f,@function\n"
   "glVertexAttrib4f:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1016(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glVertexAttrib4fv\n"
   ".type glVertexAttrib4fv,@function\n"
   "glVertexAttrib4fv:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1024(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glVertexAttribIPointer\n"
   ".type glVertexAttribIPointer,@function\n"
   "glVertexAttribIPointer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1032(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glVertexAttribPointer\n"
   ".type glVertexAttribPointer,@function\n"
   "glVertexAttribPointer:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1040(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glViewport\n"
   ".type glViewport,@function\n"
   "glViewport:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1048(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   ".globl glWaitSync\n"
   ".type glWaitSync,@function\n"
   "glWaitSync:\n"
   "  movq orbis_gl_slot@GOTPCREL(%rip), %rax\n"
   "  movq 1056(%rax), %rax\n"
   "  testq %rax, %rax\n"
   "  je orbis_gl_thunk_bad\n"
   "  jmpq *%rax\n"
   "orbis_gl_thunk_bad:\n"
   "  jmp orbis_gl_unresolved\n"
);
